### ISSUE TITLE
老哥  这个文件可不可以发一下？

### ISSUE THREAD

**Issue by FrankCreen** [coder-liusen/jobs_analysis#1]
老哥  这个文件可不可以发一下？
query_param_dir = "F:\\python_code\\analysis\\web_info\\lagou_query.txt" # 请求网页的参数文件

**Comment by coder-liusen** [comment]
您好，仓库里有这个文件。这个路径参数改一下就可以了。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"FungChen"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月5日(星期二) 晚上9:39
收件人:&nbsp;"coder-liusen/jobs_analysis"<jobs_analysis@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[coder-liusen/jobs_analysis] 老哥  这个文件可不可以发一下？ (#1)





 
老哥  这个文件可不可以发一下？
 query_param_dir = "F:\python_code\analysis\web_info\lagou_query.txt" # 请求网页的参数文件

**Comment by FrankCreen** [comment]
好的，谢谢~

**Comment by FrankCreen** [comment]
好的，谢谢~
